### ISSUE TITLE
How to determine if an attribute is present?

### ISSUE THREAD

**Issue by mcordova1967** [eteran/cpp-json#12] opened 2022-03-09 02:16 UTC
Hello, I am using the array/iterator facilities to navigate each object of a certain array, but some fields/attributes may be missing in some of the objects, the library is throwing an error if I try to obtain a value of a non-existent field:

terminate called after throwing an instance of 'json::invalid_index'

I tried is_null but it does not work because I have to retrieve the value first and the exception gets triggered.

Any help will be greatly appreciated.
Thank you.

ps: Very nice library, I started a hello world right away, I am parsing mostly, the iterator is great, I just hit this aparent limitation in the API, I cannot find a contains() or has_attribute() function

**Comment by eteran** [comment] 2022-03-10 15:19
If you are looking at a json object and are unsure if it has a specific key, you can use:

```
if(has_key(obj, "my_key")) {
    const json::value &v = obj["my_key"];
}
```

Let me know if this helps!

**Comment by eteran** [comment] 2022-03-10 18:43
Closing as duplicate of https://github.com/eteran/cpp-json/issues/13

**Closed** 2022-03-14 17:39 UTC
